<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22562" started-at="2016-12-01T19:43:17Z" finished-at="2016-12-01T19:43:39Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="22562" started-at="2016-12-01T19:43:17Z" finished-at="2016-12-01T19:43:39Z">
      <class name="TestCaseFactory.LogInPageTC">
        <test-method status="PASS" signature="urlSetUp()[pri:0, instance:TestCaseFactory.LogInPageTC@91161c7]" name="urlSetUp" is-config="true" duration-ms="8731" started-at="2016-12-02T01:13:17Z" finished-at="2016-12-02T01:13:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- urlSetUp -->
        <test-method status="FAIL" signature="VerifyUserLogin()[pri:0, instance:TestCaseFactory.LogInPageTC@91161c7]" name="VerifyUserLogin" duration-ms="1382" started-at="2016-12-02T01:13:25Z" finished-at="2016-12-02T01:13:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at TestCaseFactory.LogInPageTC.VerifyUserLogin(LogInPageTC.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserLogin -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:TestCaseFactory.LogInPageTC@91161c7]" name="tearDown" is-config="true" duration-ms="871" started-at="2016-12-02T01:13:27Z" finished-at="2016-12-02T01:13:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=VerifyUserLogin status=FAILURE method=LogInPageTC.VerifyUserLogin()[pri:0, instance:TestCaseFactory.LogInPageTC@91161c7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="asdad()[pri:0, instance:TestCaseFactory.LogInPageTC@91161c7]" name="asdad" duration-ms="10405" started-at="2016-12-02T01:13:28Z" finished-at="2016-12-02T01:13:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- asdad -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:TestCaseFactory.LogInPageTC@91161c7]" name="tearDown" is-config="true" duration-ms="1" started-at="2016-12-02T01:13:38Z" finished-at="2016-12-02T01:13:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=asdad status=SUCCESS method=LogInPageTC.asdad()[pri:0, instance:TestCaseFactory.LogInPageTC@91161c7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="BeforeTest()[pri:0, instance:TestCaseFactory.LogInPageTC@91161c7]" name="BeforeTest" is-config="true" duration-ms="1152" started-at="2016-12-02T01:13:38Z" finished-at="2016-12-02T01:13:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeTest -->
      </class> <!-- TestCaseFactory.LogInPageTC -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
